## 读取数据集

In [32]:
# 创建一个数据集 ../data/house_tiny.csv
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')  

In [33]:
# 从数据集中读取数据
import pandas as pd

data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

## 处理缺失值

"NaN"代表缺失值，为了处理确实的数据，一般采用插值或删除的方法。

In [34]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

对于inputs中的**类别值**或**离散值**，将"NaN"视为一个类别。

由于Alley只接收两种类型"Alley"和"NaN"，pandas自动的将Alley转化为"Alley_Pave"和"Alley_nan"。

In [36]:
inputs = pd.get_dummies(inputs, dummy_na=True) # dummy_na 表示生成列Alley_nan
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

## 转换为张量

In [37]:
import torch

X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

## 练习
1. 删除缺失值最多的列。
2. 将预处理后的数据集转换为张量格式。

In [74]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_test.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Bathrooms,Alley,Price\n')  # 列名
    f.write('NA,1,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,NA,106000\n')
    f.write('4,NA,NA,178100\n')
    f.write('NA,NA,AK,140000\n') 

In [75]:
import pandas as pd
data = pd.read_csv(data_file)
data

NumRooms  Bathrooms Alley   Price
0       NaN        1.0  Pave  127500
1       2.0        NaN   NaN  106000
2       4.0        NaN   NaN  178100
3       NaN        NaN    AK  140000

In [76]:
inputs, outputs = data.iloc[:, 0:3], data.iloc[:, 3]
inputs

NumRooms  Bathrooms Alley
0       NaN        1.0  Pave
1       2.0        NaN   NaN
2       4.0        NaN   NaN
3       NaN        NaN    AK

In [77]:
inputs.count().min(), inputs.count().idxmin()

(1, 'Bathrooms')

In [78]:
inputs = inputs.drop(inputs.count().idxmin(), axis=1)
inputs

NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN    AK

In [79]:
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0    AK

In [80]:
inputs = pd.get_dummies(inputs, dummy_na=True) # dummy_na 表示生成列Alley_nan
inputs

NumRooms  Alley_AK  Alley_Pave  Alley_nan
0       3.0         0           1          0
1       2.0         0           0          1
2       4.0         0           0          1
3       3.0         1           0          0

In [81]:
import torch
X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 0., 1., 0.],
         [2., 0., 0., 1.],
         [4., 0., 0., 1.],
         [3., 1., 0., 0.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))