## 数据操作

（1）获取数据

（2）处理数据

PyTorch和TensorFlow中的Tensor和python中Numpy的ndarray类似，但是比Numpy多一些功能，其中最重要的是Tensor这种张量类支持自动微分，更适合深度学习。

In [1]:
import torch

In [2]:
# 创建长度为12的一维向量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# 查看张量的形状，每个维度的大小
x.shape

torch.Size([12])

In [4]:
# 查看张量元素的个数
x.numel()

12

In [5]:
# 改变张量的形状
X = x.reshape(3, 4)
# X = x.reshape(-1, 4)
# X = x.reshape(3, -1)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
# 创建一个全0的张量
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
# 创建一个全1的张量
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
# 创建一个随机初始化的张量，均值为0、标准差为1的正态分布
torch.randn(3, 4)

tensor([[ 0.6752,  0.8690, -0.8258, -0.0835],
        [ 0.3145,  0.1149,  0.7123,  1.7537],
        [ 0.2813,  0.4841,  0.0054,  0.2556]])

In [9]:
# 创建一个指定数值的张量
torch.tensor([[1, 2, 3, 4], [2, 3, 4, 4], [2, 3, 3, 3]])

tensor([[1, 2, 3, 4],
        [2, 3, 4, 4],
        [2, 3, 3, 3]])

## 运算

In [10]:
# 按元素运算 +, -, *, /, **
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1,  4, 16, 64]))

In [11]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [12]:
# 张量的合并，分为垂直和水平
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[0, 2, 3, 3], [2, 3, 4, 4], [2, 3, 3, 3]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 0.,  2.,  3.,  3.],
         [ 2.,  3.,  4.,  4.],
         [ 2.,  3.,  3.,  3.]]),
 tensor([[ 0.,  1.,  2.,  3.,  0.,  2.,  3.,  3.],
         [ 4.,  5.,  6.,  7.,  2.,  3.,  4.,  4.],
         [ 8.,  9., 10., 11.,  2.,  3.,  3.,  3.]]))

In [13]:
# 逻辑运算，判断相同位置的元素是否相等
X == Y

tensor([[ True, False, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [14]:
# 对所有元素求和
X.sum()

tensor(66.)

## 广播

广播的运行机制是，首先通过适当的复制元素来扩展一个或两个数组，以便在做转换时，两个张量具有相同的形状，其次对生成的数组执行按元素操作。

多数情况下，沿着数组中长度为1的轴进行广播。

In [15]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [16]:
# a复制列，b复制行
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 索引和切片

In [17]:
# -1定位到最后一个元素，1:3选取第二个和第三个元素
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [18]:
# 为单个元素赋值
X[1, 2] = 100
X

tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5., 100.,   7.],
        [  8.,   9.,  10.,  11.]])

In [19]:
# 为多个元素赋值

In [20]:
X[0:2, :] = 110
X

tensor([[110., 110., 110., 110.],
        [110., 110., 110., 110.],
        [  8.,   9.,  10.,  11.]])

## 节省内存

python中Y = X + Y，计算前后Y的地址不同，系统为X + Y的结果重新分配了内存，这样就造成了内存的浪费，而且多个变量同时指向Y，在执行操作后，其他变量仍然会指向旧的地址。

In [21]:
# 内存浪费
before = id(Y)
Y = Y + X
id(Y) == before

False

In [22]:
# 原地修改
Z = torch.zeros_like(Y)
print('id(X):', id(Z))
Z[:] = X + Y
print('id(X):', id(Z))

id(X): 140420690748928
id(X): 140420690748928


In [23]:
before = id(X)
X += Y
id(X) == before

True

## 对象转换

tensor => numpy

numpy => tensor

tensor => python

In [24]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [25]:
# 大小为1的装量转为python标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 练习

In [26]:
# 1.将本节中的条件语句 X == Y 更改为 X < Y 或 X > Y，然后看看你可以得到什么样的张量。
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[0, 2, 3, 3], [2, 3, 4, 4], [2, 3, 3, 3]])
X > Y, X < Y

(tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[False,  True,  True, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [27]:
# 2. 用其他形状（例如三维张量）替换广播机制中按元素操作的两个张量。结果是否与预期相同？
a = torch.tensor([[[1, 1, 1]], [[2, 2, 2]]])
b = torch.tensor([[[10, 10, 10], [20, 20, 20], [30, 30, 30]]])
a.shape, b.shape

(torch.Size([2, 1, 3]), torch.Size([1, 3, 3]))

In [28]:
a + b

tensor([[[11, 11, 11],
         [21, 21, 21],
         [31, 31, 31]],

        [[12, 12, 12],
         [22, 22, 22],
         [32, 32, 32]]])