## 不带参数的层

In [1]:
import torch
from torch import nn
import torch.nn.functional as F

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
# 检测随机数据的均值是否为0（建全性检查）
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-2.7940e-09, grad_fn=<MeanBackward0>)

## 带参数的层

In [4]:
class MyLinear(nn.Module):
    def __init__(self, in_dims, out_dims):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_dims, out_dims))
        self.bias = nn.Parameter(torch.randn(out_dims,))
        
    def forward(self, X):
        linear = torch.matmul(X, self.weight) + self.bias
        return F.relu(linear)

In [5]:
linear = MyLinear(5, 3)
linear.weight, linear.bias

(Parameter containing:
 tensor([[ 0.7661,  0.8207, -2.4059],
         [ 0.6740,  0.0647, -0.4931],
         [ 1.2469,  1.1992, -0.2244],
         [-0.0808,  0.4517,  0.5270],
         [-0.8878, -0.5673, -2.3923]], requires_grad=True),
 Parameter containing:
 tensor([ 2.0688, -0.7591,  0.8815], requires_grad=True))

In [6]:
linear(torch.rand(2, 5))

tensor([[2.5005, 0.0000, 0.2177],
        [3.2408, 0.8144, 0.0000]], grad_fn=<ReluBackward0>)

In [7]:
# 使用自定义层构建模型
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.0000],
        [0.0457]], grad_fn=<ReluBackward0>)